### ISSUE TITLE
Bug info

### ISSUE THREAD

**Issue by yonaskolb** [toshi0383/ImageOverlay#1]
Do you have any more info about the Apple bug you mention? I'm using `UIImage.overlayContentView` in tvOS 11 and it seems to stop working if I change the image at all via Kingfisher which makes it unusable in a `UICollectionViewCell`

**Comment by toshi0383** [comment]
Hi @yonaskolb 
In my experience, as long as you don't nil-out the `imageView.image`, it works fine.
Can you share the piece of sourcecode if possible?

**Comment by yonaskolb** [comment]
I'm using https://github.com/onevcat/Kingfisher so the setting of the image is internal. If I set a placeholder image it breaks straight away. If I don't then when the cell is recycled and get's a new image it breaks
```
kf.setImage(with: image.url, placeholder: placeholder, options: options)
```

**Comment by yonaskolb** [comment]
Have you found a way to fix the issue? Say the image gets set to nil, is there a way to re attach the overlays? I've tried re-adding the overlays to the `overlayContentView` but that doesn't work

**Comment by toshi0383** [comment]
In my experience there is no way to recover.
So just don’t nil-out. I use Kingfisher as well, but not that `setImage` API.

**Comment by toshi0383** [comment]
Please feel free to reopen for further questions!👌
